#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
# autospec version: v18
# autospec commit: f35655a
#
Name     : libgbinder
Version  : 1.1.40
Release  : 2
URL      : https://github.com/mer-hybris/libgbinder/archive/1.1.40/libgbinder-1.1.40.tar.gz
Source0  : https://github.com/mer-hybris/libgbinder/archive/1.1.40/libgbinder-1.1.40.tar.gz
Summary  : Binder client library
Group    : Development/Tools
License  : BSD-3-Clause
Requires: libgbinder-lib = %{version}-%{release}
Requires: libgbinder-license = %{version}-%{release}
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(libglibutil)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
C interfaces for Android binder

%package dev
Summary: dev components for the libgbinder package.
Group: Development
Requires: libgbinder-lib = %{version}-%{release}
Provides: libgbinder-devel = %{version}-%{release}
Requires: libgbinder = %{version}-%{release}

%description dev
dev components for the libgbinder package.


%package lib
Summary: lib components for the libgbinder package.
Group: Libraries
Requires: libgbinder-license = %{version}-%{release}

%description lib
lib components for the libgbinder package.


%package license
Summary: license components for the libgbinder package.
Group: Default

%description license
license components for the libgbinder package.


%prep
%setup -q -n libgbinder-1.1.40
cd %{_builddir}/libgbinder-1.1.40

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1724884136
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
make  %{?_smp_mflags}


%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1724884136
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libgbinder
cp %{_builddir}/libgbinder-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/libgbinder/a0e86b471ed91166f534f2e9717a38c5710a4cae || :
cp %{_builddir}/libgbinder-%{version}/debian/copyright %{buildroot}/usr/share/package-licenses/libgbinder/a0e86b471ed91166f534f2e9717a38c5710a4cae || :
export GOAMD64=v2
GOAMD64=v2
%make_install LIBDIR=/usr/lib64 install-dev

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/gbinder/gbinder.h
/usr/include/gbinder/gbinder_bridge.h
/usr/include/gbinder/gbinder_buffer.h
/usr/include/gbinder/gbinder_client.h
/usr/include/gbinder/gbinder_eventloop.h
/usr/include/gbinder/gbinder_fmq.h
/usr/include/gbinder/gbinder_local_object.h
/usr/include/gbinder/gbinder_local_reply.h
/usr/include/gbinder/gbinder_local_request.h
/usr/include/gbinder/gbinder_reader.h
/usr/include/gbinder/gbinder_remote_object.h
/usr/include/gbinder/gbinder_remote_reply.h
/usr/include/gbinder/gbinder_remote_request.h
/usr/include/gbinder/gbinder_servicemanager.h
/usr/include/gbinder/gbinder_servicename.h
/usr/include/gbinder/gbinder_types.h
/usr/include/gbinder/gbinder_writer.h
/usr/lib64/libgbinder.so
/usr/lib64/pkgconfig/libgbinder.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgbinder.so.1
/usr/lib64/libgbinder.so.1.1
/usr/lib64/libgbinder.so.1.1.40

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libgbinder/a0e86b471ed91166f534f2e9717a38c5710a4cae
